.\"
.\" (C) Copyright 2014 David Suárez <david.sephirot@gmail.com>
.\"

.TH "KDECONNECT-CLI" "1" "July 2014"

.SH NAME
kdeconnect-cli - KDE Connect CLI tool

.SH SYNOPSIS
.B kdeconnect-cli
[\fI\,Qt-options\/\fR] [\fI\,KDE-options\/\fR] [\fI\,options\/\fR]

.SH DESCRIPTION
KDE Connect CLI tool

.SS "Generic options:"
.TP
\fB\-\-help\fR
Show help about options
.TP
\fB\-\-help\-qt\fR
Show Qt specific options
.TP
\fB\-\-help\-kde\fR
Show KDE specific options
.TP
\fB\-\-help\-all\fR
Show all options
.TP
\fB\-\-author\fR
Show author information
.TP
\fB\-v\fR, \fB\-\-version\fR
Show version information
.TP
\fB\-\-license\fR
Show license information
.TP
\fB\-\-\fR
End of options

.SH OPTIONS
.TP
\fB\-l\fR, \fB\-\-list\-devices\fR
List all devices
.TP
\fB\-\-share\fR <path>
Share a file to a said device
.TP
\fB\-\-pair\fR
Request pairing to a said device
.TP
\fB\-\-unpair\fR
Stop pairing to a said device
.TP
\fB\-\-ping\fR
Sends a ping to said device
.TP
\fB\-\-device\fR <dev>
Device ID
.PP
KDE Development Platform: 4.13.1
kdeconnect\-cli: 1.0
